/* GEN:headerstart */
/**
 * This interface acts as a BSJ proxy node factory for the standard BSJ compiler.  This interface should not be exposed
 * to the public compiler API as type safety depends on it being used in a constrained way.
 * 
 * @author Zachary Palmer
 */
/* GEN:headerstop */
public interface BsjNodeProxyFactory
{
	/* GEN:start */
    /**
     * Retrieves a mapping from the IDs of nodes generated by this proxy to the IDs of nodes that they wrapped.
     */
    public BijectiveMap<Long,Long> getProxyIdMapping();
	/* GEN:stop */
}